### ISSUE TITLE
Skip all but the first test

### ISSUE THREAD

**Issue by tejasbubane** [exercism/clojure#123]
Most of the languages I work with on `exercism` have all but the first test skipped. Makes it easy to work through the exercises unskipping tests one by one making them pass.
When I run `lein test` before writing any code, all tests fail with a bunch of errors.

Was it intentional to keep all tests open here in `xclojure`?

**Comment by kytrinyx** [comment]
Another related question—does leiningen have a _fail fast_ option? That would also help in that it would stop after the first failure.

**Comment by yurrriq** [comment]
I'm not sure about skipping tests. I guess I don't use languages where that's common, but indefinite see the utility. Iirc failing tests can be awfully revealing sometimes too. Id be happy to review and merge a PR that adds some sort of test skipping. Worst case we could comment out (`;;` please) all but the first year and document that you have to uncomment them.

Re: Leiningen failing fast. I don't think so. I think it just evaluates all the cars with `:test` metadata. While we're on the subject of testing experience. Is there any mention of `lein-auto` anywhere? That might be a good addition too. `lein auto test` would watch files for changes and run the tests after.

**Comment by kytrinyx** [comment]
> Is there any mention of lein-auto anywhere?

You asked briefly in https://github.com/exercism/xclojure/pull/88 but nobody responded.

I think it could be worth mentioning, or if there's a great article somewhere (or in-depth tutorial on using lein and related tools), maybe we could point to that.

**Comment by tejasbubane** [comment]
Found [a library](https://github.com/pjstadig/lein-fail-fast) which adds lein hook for fail-fast. But adding it as a dependency for all exercises seems like an overkill in this case.

> Worst case we could comment out (;; please) all but the first year and document that you have to uncomment them.

Commented code looks ugly IMO (with syntax highlighting in editor) and gives an impression that it is some kind of docstring at first glance. We can use `'` (`quote`) instead and ask people to unquote (remove the quote) as they go on solving the exercise. With quote the code seems to present in place as opposed to comments.

**Comment by yurrriq** [comment]
Fair point about syntax highlighting. There's also `(comment ...)`, but the fail fast solution sounds cleaner overall and I think obviates the need for commenting or quoting.
