### ISSUE TITLE
Discuss tooling

### ISSUE THREAD

**Issue by yurrriq** [exercism/clojure#124]
Per discussion elsewhere (TODO: add link) we should mention lein-auto somewhere. We also might want to mention/use clj-fmt or some other linter.

**Comment by tejasbubane** [comment]
`lein-auto` discussion came from here: https://github.com/exercism/xclojure/issues/123#issuecomment-236680694

> We also might want to mention/use clj-fmt or some other linter.

[Related discussion](https://github.com/exercism/rikki) in `xcrystal` where Katrina strongly recommends use of formatting/linting tools and suggests adding automated [rikki](https://github.com/exercism/rikki) nitpicks using such formatters. 

Does clojure have a standard formatter like eg. [`gofmt`](https://golang.org/cmd/gofmt/) for golang?

**Comment by kytrinyx** [comment]
> where Katrina strongly recommends use of formatting/linting tools

I only strongly recommend it if it's part of the culture in the language. In Ruby, for example, I'd recommend against making strict rules about linting/formatting, but I might suggest that we introduce people to rubocop as a thing they can explore. In Go the culture is so strong that it makes sense to automate it.
