### ISSUE TITLE
Recommend a linter for Clojure?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/clojure#14]
See exercism/docs#54 for details.

**Comment by canweriotnow** [comment]
kibit is also easy to integrate into emacs:

```elisp
;; kibit

;; Teach compile the syntax of the kibit output
(require 'compile)
(add-to-list 'compilation-error-regexp-alist-alist
             '(kibit "At \\([^:]+\\):\\([[:digit:]]+\\):" 1 2 nil 0))
(add-to-list 'compilation-error-regexp-alist 'kibit)

;; A convenient command to run "lein kibit" in the project to which
;; the current emacs buffer belongs to.
(defun kibit ()
  "Run kibit on the current project.
Display the results in a hyperlinked *compilation* buffer."
  (interactive)
  (compile "lein kibit"))

(defun kibit-current-file ()
  "Run kibit on the current file.
Display the results in a hyperlinked *compilation* buffer."
  (interactive)
  (compile (concat "lein kibit " buffer-file-name)))
```

But as @mathias pointed out, kibit's more about writing 'idiomatic' code than traditional linting... and it is showing its age... was just discussing this on #clojure IRC yesterday.

@kytrinyx is there a thread on the `leinify` cmd addition? I'm trying to keep pace with the CLI in exercism-emacs package, and I could see some really useful support from CIDER and clojure-mode in doing an 'enhanced' leinification from within emacs.

FWIW, I liked the lack of a project.clj in the exercises, helped to keep it simple, and removed direct support for 3rd party libs I discussed in #39

**Comment by kytrinyx** [comment]
We have a thread open here: https://github.com/exercism/cli/issues/102 -- it stalled a bit because I got ridiculously busy, but now that there are 3 core contributors to the CLI package, things have been moving more quickly again.

**Comment by canweriotnow** [comment]
Ah, gotcha. Just commented there with some suggestions on how to achieve this... it occurs to me after the fact that the lein-template suggestion I made over there would also ease access for exercism-emacs or any other editor packages/tools people wanted to write.

**Comment by kytrinyx** [comment]
That would be cool. Anything to lower the barrier to tool-writing seems like a good thing in my book.

**Comment by canweriotnow** [comment]
How about adding [squiggly-clojure](https://github.com/clojure-emacs/squiggly-clojure) to the default project.clj, it uses Eastwood and core.typed w/ Flycheck to lint as you type... I guess that's mainly of help to emacs users, but I think there are some similar things for other editors. 

It would be interesting to do a survey of editor usage/preference per-track and across the board...

**Comment by kytrinyx** [comment]
I'm down with that. A survey would be interesting... I wonder what the easiest way to implement that would be (external tool, presumably?)
