### ISSUE TITLE
Add/require stubs for all exercises

### ISSUE THREAD

**Issue by canweriotnow** [exercism/clojure#144]
Re conversation on #121 - make stubs a standard feature of clojure track projects... this is actually bringing clojure track closer to typical for the other Lisp family tracks, which IIRC provide basic structure templates for solutions.

TODO:
- [x] Stub all existing exercises
- [ ] Add stub instructions to CONTRIBUTING guide
- [ ] Add test-for-presence-of-stub to test suite.
- [ ] intelligent stub generator script for new exercises in `bin/` (maybe?)

**Comment by haus** [comment]
I broke out the first checklist item into #205
