### ISSUE TITLE
Clock tests weren't cleaned up?

### ISSUE THREAD

**Issue by tstirrat15** [exercism/clojure#182]
[See here](https://github.com/exercism/clojure/blob/master/exercises/clock/clock.mustache).

I can see that that template was used to generate tests, but it wasn't cleaned up afterwards, which is potentially confusing to users.

Is there some cleanup process that didn't run?

**Comment by yurrriq** [comment]
I don't follow. Could you please describe what, specifically, needs to be cleaned up?

**Comment by tstirrat15** [comment]
The .mustache file. Isn't that a vestige of the build process that shouldn't be around once the tests are built?

**Comment by yurrriq** [comment]
Ah, see. :+1: to excluding it from the user-facing side.

**Comment by tstirrat15** [comment]
Should the build process automatically delete these? I couldn't grok how the build process works and wanted that to be fixed if it needed to be fixed. Otherwise I'm happy to submit a PR that just deletes all of the `.mustache`s from this repo.

**Comment by yurrriq** [comment]
Deleting the mustache files is definitely incorrect. We just need to move them or otherwise prevent users from seeing them with they fetch from the Clojure track.

**Comment by yurrriq** [comment]
@kytrinyx, any advice here? I know we've used `_src/` et al. before.

**Comment by haus** [comment]
Yea, we're already using `_src`, so the templates could just move there and the generator be updated to account for the change. (unless there's an easy way to exclude the mustache files from being fetched).

**Comment by kytrinyx** [comment]
We have a couple of ways of making sure things don't get fetched.

The first (and probably cleanest) is to stick everything you don't want fetched into a `.meta/` directory within the exercise directory. So `$ROOT/exercises/clock/.meta/$FILE`.

The other is to add a key `ignore_pattern` to the `config.json` (see https://github.com/exercism/docs/blob/master/language-tracks/configuration/README.md) which matches anything that should not be served to the user.

The `.meta/` directory would be a great place to put any build artifacts as well as the example solution.

**Comment by haus** [comment]
@tstirrat15 i think this should be resolved with the linked PR, so i'm going to close it for now. if it is still an issue, please reopen it.

**Comment by tstirrat15** [comment]
Looks good to me. Thank you!
