### ISSUE TITLE
Error in nucleotide-count test cases

### ISSUE THREAD

**Issue by developer2019** [exercism/clojure#198]
Those test cases in https://github.com/exercism/clojure/blob/master/exercises/nucleotide-count/test/nucleotide_count_test.clj doesn't make sense.
```
(deftest repetitive-sequence-has-only-guanosine
  (is (= {\A 0, \T 0, \C 0, \G 8}
         (nucleotide-count/nucleotide-counts "GGGGGGGG"))))

(deftest empty-dna-strand-has-no-nucleotides
  (is (= {\A 0, \T 0, \C 0, \G 0}
         (nucleotide-count/nucleotide-counts ""))))
```
Should be `{\G 8}` and `{}` respectively.

**Comment by yurrriq** [comment]
Thanks for your feedback. Please provide more information about why this doesn't make sense to you. The [example implementation](https://github.com/exercism/clojure/blob/master/exercises/nucleotide-count/src/example.clj) produces output as those tests expect. Are you suggesting we need to change that as well? If so, can you provide some documentation thereof?

**Comment by developer2019** [comment]
@yurrriq Thanks for response. It makes sense after second read. Haven't noticed that it uses zeros.
