### ISSUE TITLE
src folder missing with beer-song exercise

### ISSUE THREAD

**Issue by heyarne** [exercism/clojure#199]
Hey there,
somehow `exercism fetch` fetched the beer-song exercise without a `src` folder. I head to create `src` and `beer_song.clj` myself because emacs didn't find them. Can I somehow help fix this?

**Comment by haus** [comment]
@heyarne we have an open issue about adding stubs to all exercises: https://github.com/exercism/clojure/issues/144

If you wanted to open a PR adding beer_song.clj with an empty function in it, that would help the next person.

**Comment by haus** [comment]
I tried this out again and the merged PR has addressed this, so I'm going to close it out. Thanks again @heyarne
