### ISSUE TITLE
Stub all existing exercises

### ISSUE THREAD

**Issue by haus** [exercism/clojure#205]
Here is a list of all of the exercises that currently exist:

- [x] accumulate
- [x] acronym
- [x] all-your-base
- [x] allergies
- [x] anagram
- [x] atbash-cipher
- [x] bank-account
- [x] beer-song
- [x] binary-search-tree
- [x] binary-search
- [x] binary
- [x] bob
- [x] bracket-push
- [x] change
- [x] clock
- [x] collatz-conjecture
- [x] complex-numbers
- [x] crypto-square
- [x] diamond
- [x] difference-of-squares
- [x] etl
- [x] flatten-array
- [x] gigasecond
- [x] grade-school
- [x] grains
- [x] hamming
- [x] hello-world
- [x] hexadecimal
- [x] isbn-verifier
- [x] isogram
- [x] kindergarten-garden
- [x] largest-series-product
- [x] leap
- [x] luhn
- [x] meetup
- [x] minesweeper
- [x] nth-prime
- [x] nucleotide-count
- [x] octal
- [x] pangram
- [x] pascals-triangle
- [x] perfect-numbers
- [x] phone-number
- [x] pig-latin
- [x] pov
- [x] prime-factors
- [x] protein-translation
- [x] proverb
- [x] queen-attack
- [x] raindrops
- [x] reverse-string
- [x] rna-transcription
- [x] robot-name
- [x] robot-simulator
- [x] roman-numerals
- [x] rotational-cipher
- [x] run-length-encoding
- [x] say
- [x] scrabble-score
- [x] secret-handshake
- [x] series
- [x] sieve
- [x] space-age
- [x] spiral-matrix
- [x] strain
- [x] sublist
- [x] sum-of-multiples
- [x] triangle
- [x] trinary
- [x] word-count
- [x] wordy

**Comment by CrowsVeldt** [comment]
I'd be happy contribute. Is there more to it than adding an {exercise-name}.clj file with the appropriate namespace and functions declerations?

**Comment by CrowsVeldt** [comment]
I believe all exercises have stub files with PR #233, although I think there's still room for improvement in terms of consistency and clarity.

**Comment by CrowsVeldt** [comment]
I've done another pass and caught to exercises I missed previously, as well as editing the stub files for greater consistency.

**Comment by haus** [comment]
Nice. This looks all done thanks @CrowsVeldt !
