### ISSUE TITLE
Series: Tests seemed to imply that the return value must be a vector, but accept lists as well

### ISSUE THREAD

**Issue by CrowsVeldt** [exercism/clojure#227]
All but one of the tests check the return value of `slices` against a vector (the exception being `number<string` which checks against a set), at first I assumed this meant that the
return value was supposed to be a `vector` specifically, but then I realized that all the tests will
pass if given a `list` instead. I assume because they're both seqs?

Clearly this isn't a major issue, but I did find it quite confusing at first. Is the returned value supposed to be a vector, specifically? If so, maybe the tests should be changed. If not, than maybe it should be made explicit? Either by the tests being rewritten, or perhaps just by adding a note in the README.

**Comment by tasxatzial** [comment]
I believe this issue is similar to #229 opened by the same person.

**Comment by tasxatzial** [comment]
@CrowsVeldt You made a great point. In exercises involving vectors, tests will generally pass even if a solution returns a list, as the container type is often ignored in equality checks. While students are free to return any structure, we don't want to imply that they should limit themselves to vectors.

Moving forward, we'll consider your feedback as we refine existing tests. We'll close this issue soon but will likely reference it in a new issue that proposes changes to the current test structure.
