### ISSUE TITLE
Rename nucleotide-count/count to avoid shadowing clojure.core/count?

### ISSUE THREAD

**Issue by CrowsVeldt** [exercism/clojure#228]
I don't imagine this is a major problem or anything, but maybe it'd avoid some inexperienced programmers (like myself) avoid confusion.

I'm not sure what a good alternative might be, maybe `amount`. Or maybe `count` could become `nucleotide-count` and the current `nucleotide-counts` could become `nucleotide-totals`.

**Comment by CrowsVeldt** [comment]
[I forgot to add the url to the test file](https://github.com/exercism/clojure/blob/master/exercises/nucleotide-count/test/nucleotide_count_test.clj)

**Comment by haus** [comment]
Addressed in #273
