### ISSUE TITLE
phone-number: README doesn't mention the functions area-code and pretty print

### ISSUE THREAD

**Issue by CrowsVeldt** [exercism/clojure#230]
The README references the `number` function, but the others are only mentioned in the test suite.
I'll try to put together a PR for this in the next couple of days.

**Comment by tasxatzial** [comment]
Both area-code and pretty print and are no longer required by the current problem specs. I've prepared a PR that will re-sync everything, but solutions will be broken since the current tests are outdated and incomplete. @bobbicodes Should i push this?

**Comment by bobbicodes** [comment]
I'd say go for it :)
