### ISSUE TITLE
clojure namespace as function name

### ISSUE THREAD

**Issue by pouya-abbassi** [exercism/clojure#253]
In [nucleotide-count](https://github.com/exercism/clojure/tree/master/exercises/nucleotide-count) exercise, main function is called `count` which is a `clojure.core` function name. And you can't change it unless you change the tests.
As far as i know, you should avoid using the same names as `clojure.core` defines.

Is it a mistake or you want to teach how to use`:refer-clojure`?

**Comment by yurrriq** [comment]
Nice catch! Seems like a good time to introduce `:refer-clojure` to me.

**Comment by AndreaCrotti** [comment]
I would simply rename the function to something else imho

**Comment by yurrriq** [comment]
Pull requests are most welcome!

**Comment by haus** [comment]
Addressed with #273
