### ISSUE TITLE
Track is missing introduction

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/clojure#265]
The [track page](https://exercism.io/my/tracks/clojure) is showing the "TODO" text underneath the track title because no introduction has been added.

**Comment by AndreaCrotti** [comment]
I don't see any TODO there and the Clojure track page looks like all the others really, so it can be closed maybe @PatrickMcSweeny ?

**Comment by PatrickMcSweeny** [comment]
![screenshot from 2019-03-08 09-07-32](https://user-images.githubusercontent.com/1254212/54033224-bc76ce00-4181-11e9-9f70-39f233e91418.png)

**Comment by PatrickMcSweeny** [comment]
The 'blurb' value needs to be filled in:

https://github.com/exercism/clojure/blob/master/config.json#L4

**Comment by AndreaCrotti** [comment]
Ah right I actually see something different when I'm logged in, that's why
<img width="1223" alt="screen shot 2019-03-08 at 17 22 33" src="https://user-images.githubusercontent.com/53640/54044420-d25ab200-41c6-11e9-8c76-a84ba6f3235d.png">

**Comment by haus** [comment]
I opened a PR here with a brief blurb (https://github.com/exercism/clojure/pull/269). If anyone has a chance to look it over that would be awesome.

**Comment by haus** [comment]
This has been resolved with #269.
