### ISSUE TITLE
All Clojure 'Extra Exercises' are rated as 'Easy'.

### ISSUE THREAD

**Issue by adc17** [exercism/clojure#274]
All extra exercises on this track are rated as easy, even though that doesn't seem to be the case.

e.g. I recently completed the 'Spiral Matrix' exercise—I found it pretty challenging, and while browsing the solutions of other users, I didn't see any that were trivial to implement.

I suspect what's actually happened is the exercises haven't been ranked correctly. If that's true, how can we fix it?

**Comment by haus** [comment]
The rankings for exercises live in https://github.com/exercism/clojure/blob/master/config.json which has an element for each exercise called difficulty. Those have just never been updated. If you (or someone) would like to take a stab at updating them in a PR that would be awesome.

**Comment by adc17** [comment]
@haus nothing fancy, I copied ratings from elsewhere (mainly Elixir). Let me know what you think.
