### ISSUE TITLE
Armstrong Numbers after Hello world?

### ISSUE THREAD

**Issue by uzilan** [exercism/clojure#276]
Does the `Armstrong Numbers` exercise really supposed to be between `Hello World` and `Two Fer`? For me it was quite a leap for a second exercise, and certainly more advanced than the string concatenation that `Two Fer` is. Just wondering if there is a thought there or if it is a mistake.

**Comment by haus** [comment]
This is only because there are no track dependencies and so it just goes by the order in `config.json`. I may just borrow another tracks dependency and ordering to maybe improve things a bit.

**Comment by porkostomus** [comment]
Was fixed by  #292 .
