### ISSUE TITLE
What was it like to learn Clojure?

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/clojure#280]
We’ve recently [started a project](https://exercism.io/blog/redesigning-tracks-in-partnership-with-chicago-university-and-sloan-foundation) to find the best way to design our tracks, in order to optimize the learning experience of students.

As a first step, we’ll be [examining the ways in which languages are unique and the ways in which they are similar](https://github.com/exercism/exercism/issues/5059). For this, we’d really like to use the knowledge of **everyone** involved in the Exercism community (students, mentors, maintainers) to answer the following questions:

1. How was your experience learning Clojure? What was helpful while learning Clojure? What did you struggle with? How did you tackle problems?
1. In what ways did Clojure differ from other languages you knew at the time? What was hard to learn? What did you have to unlearn? What syntax did you have to remap? What concepts carried over nicely?

Could you spare 5 minutes to help us by answering these questions? It would greatly help us improve the experience students have learning Clojure :)

_Note: this issue is **not** meant as a discussion, just as a place for people to post their own, personal experiences._

_Want to keep your thoughts private but still help? Feel free to email me at erik@exercism.io_

Thank you!

**Comment by davidpham87** [comment]
I don’t know if this is exclusive to those who learn Clojure on Exercism, but I can share my experience with you.

1. Learning Clojure was joy thanks to the REPL. The language was a bit different but the feedback speed was such that the syntax is assimilated quite fast. The challenges were numerous but the main one is we don’t know what is the best answer to solve particular problems at the beginning. With this respect using ClojureScript Koans and 4Clojure helped a lot.  Another issue at the time was the tooling. I use Emacs and Cider With a REPL, but it was not always stable. [I think VSCode is easier to start with now]. For the theory, Clojure for the brave and the true was great to teach the core principle of the language.

2. At the time, I had exposure to C++, mathematica, Matlab, R and python. Clojure was thus my first functional Lisp integrated to the JVM. I learned it to be able target JVM and JS VM (and CLR if necessary). Using function as value, maps as entity abstraction and namespaces as containers were both eye opening and challenging. All these notions exists in R and python, so it was nice to carry them over. I was happy to unlearn all the OOP and static typing from C++ to solve problems efficiently.

**Comment by ErikSchierboom** [comment]
We're closing this issue as it was part of our research for the v3 version of Exercism which has [just been released](https://exercism.org/blog/exercism-v3-has-launched).

Thanks everyone for chipping in! It has been greatly appreciated.
