### ISSUE TITLE
[Scrabble Score] Use char in score-letter

### ISSUE THREAD

**Issue by gabriel376** [exercism/clojure#283]
Exercise Scrabble Score has two functions:
```Clojure
(defn score-letter [] ;; <- arglist goes here
      ;; your code goes here
)

(defn score-word [] ;; <- arglist goes here
  ;; your code goes here
)
```

I think it's kinda strange that `score-letter` parameter is string rather than a char:
```Clojure
(deftest lower-case-letter
  (is (= 1 (scrabble-score/score-letter "a"))))

(deftest bigger-word-1
  (is (= 6 (scrabble-score/score-word "street"))))
```

Most implementation uses a map like this:
```Clojure
{
    "A" 1, "E" 1, "I" 1, "O" 1, "U" 1, "L" 1, "N" 1, "R" 1, "S" 1, "T" 1,
    "D" 2, "G" 2,
    "B" 3, "C" 3, "M" 3, "P" 3,
    "F" 4, "H" 4, "V" 4, "W" 4, "Y" 4,
    "K" 5,
    "J" 8, "X" 8,
    "Q" 10, "Z" 10
}
```

My suggestion is to change `score-letter` parameter to char:
```Clojure
(deftest lower-case-letter
  (is (= 1 (scrabble-score/score-letter \a))))
```

**Comment by haus** [comment]
@gabriel376 PRs are welcome, and I think characters sound reasonable for English. I would be a little concerned that other languages might not map to 1 character per tile. For example, for a long time Spanish scrabble had tiles for 'CH', 'LL', and 'RR' and based on a brief bit of googling other languages such as Hungarian include two character tiles. I think a map of strings to integers would probably match better for those languages.
