### ISSUE TITLE
Are some tests in Luhn wrong?

### ISSUE THREAD

**Issue by 4lph4-Ph4un** [exercism/clojure#291]
"046 454 286" is expected to be true.

Yet:

```
Doubled:

0_6 _5_ 2_6

Will become:

0_3 _1_ 4_3

The sum:

  0 + 4 + 3 (7)
+ 4 + 1 + 4 (9)
+ 4 + 8 + 3 (15)
= 31
```

"055 444 285" is expected to be true.

Yet:

```
doubled:

0_5 _4_ 2_5

Will become:

0_1 _8_ 4_1

  0 + 5 + 1 (6)
+ 4 + 8 + 4 (16)
+ 4 + 8 + 1 (13)
= 35
```

"091" is expected to be true:

Yet:

```
doubled:

0_1 -> 0_2

0 + 9 + 2 = 11
```

Don't know if I've understood correctly, but it seems that the tests are inconsistent on where they expect to start doubling the numbers (are leading zeroes somehow accidentally omitted?). There's at least no mention in the instructions that leading zeroes should be omitted from the doubled sequence and it seems it's stated that the doubled numbers fall onto the even indices on the input sequence? How come it is then to be expected that 9 in "091" would be the one that's doubled?

**Comment by haus** [comment]
For Luhn, the doubled numbers are counted from the right. Every second number starting from the right, so for "091" 1 is the rightmost, so 9 is the number that will be doubled. In your first example of "046 454 286", "_4_ 4_4 _8_" are the numbers to be doubled, so

Doubled:
"_4_ 4_4 _8_"

Will become:
"_8_ 8_8 _7_"

086 (14) + 858 (21) + 276 (15) = 50, which is divisible by 10.

Leading zeroes isn't specified, but doesn't matter as counting happens from the right not the left.

**Comment by 4lph4-Ph4un** [comment]
Ah I see! well that clarifies it! And it even states that in the instructions! :) Looks like I'll add reverse next to get the tests to pass :D
