### ISSUE TITLE
"say" exercise doesn't use "and" in hundreds

### ISSUE THREAD

**Issue by Grazfather** [exercism/clojure#302]
We explicitly have a test:
```clojure
(deftest one-hundred-twenty-three-test
  (is (= "one hundred twenty-three" (say/number 123))))
```

But in the description:

- 14 becomes "fourteen".
- 100 becomes "one hundred".
- 120 becomes "one hundred **and** twenty".
- 1002 becomes "one thousand **and** two".
- 1323 becomes "one thousand three hundred **and** twenty-three".

Seems are tests are much simpler (the examples conditionally add `and` between thousands or hundreds, depending on the value).

**Comment by porkostomus** [comment]
Indeed, a look at the [problem specs](https://github.com/exercism/problem-specifications/blob/main/exercises/say/canonical-data.json) shows that the test is correct, so the description should be changed accordingly.
