### ISSUE TITLE
New clojure/concepts exercises don't have project.clj files for solving via command line

### ISSUE THREAD

**Issue by edenfull** [exercism/clojure#413]
Via the command line, I'm working through https://exercism.org/tracks/clojure/exercises/lucians-luscious-lasagna but there is no `project.clj` file in `exercism/clojure/lucians-luscious-lasagna` or any of the newer concepts recently added.

When I run `lein test`, I get this error: Couldn't find project.clj, which is needed for test.

Prior exercises all have `project.clj` files so I haven't encountered this issue before. Thank you!

**Comment by porkostomus** [comment]
Good to know folks are still using the CLI. I submitted a PR to include `project.clj` by default with the following config:

```clojure
(defproject lucians-luscious-lasagna "0.1.0-SNAPSHOT"
  :description "lucians-luscious-lasagna exercise."
  :url "https://github.com/exercism/clojure/tree/main/exercises/concept/lucians-luscious-lasagna"
  :dependencies [[org.clojure/clojure "1.10.0"]])
```

Thanks for letting us know!

**Comment by journeybeforedestination** [comment]
Speaking of cli the help file also says: 

The Clojure exercises on Exercism ship with a `deps.edn` file with a `:test` alias to invoke the [cognitect-labs test-runner](https://github.com/cognitect-labs/test-runner):

``` bash
$ clj -X:test
```

At least in the lucians-luscious-lasagna I don't see a deps.edn file setup to do this when I download the exercise using the exercism cli.
