### ISSUE TITLE
All tests passed, exercise marked as failed (Cars-assemble exercise)

### ISSUE THREAD

**Issue by garpez8bit** [exercism/clojure#424]
As the title tells, the code I submitted appears to pass all the tests, but the exercise is still marked as failed.

![sr](https://user-images.githubusercontent.com/73033318/133327105-64e75178-4c4d-44ee-a9dd-6ff6992d6eb6.png)

**Comment by porkostomus** [comment]
Hi @garpez8bit, a fix was recently applied to address this, but the exercise needs to be updated on your side. If you visit https://exercism.org/tracks/clojure/exercises/cars-assemble/ there should be a message displayed allowing you to do this.

**Comment by garpez8bit** [comment]
Thanks! Sorry, I didn't see that.
