### ISSUE TITLE
Interest-is-interesting: Should a negative balance update move closer to 0, or further away?

### ISSUE THREAD

**Issue by snits** [exercism/clojure#428]
With the way banks normally work I'd expect a negative balance to go further negative instead of approaching 0:

(is (= -0.11904801M (interest-is-interesting/annual-balance-update -0.123M)))

I think this is a result of a multiplying a negative balance with a negative interest rate, resulting in a positive yield for the adjustment.
Instead I think the more accurate thing would be to multiply the interest rate against the absolute value of the balance, so when it is negative the yield will be negative as well.

**Comment by porkostomus** [comment]
Thanks for bringing this to my attention. I made some critical errors when porting this, and now I know why! I've linked a PR to fix them.
