### ISSUE TITLE
Interest is interesting - dependence on implementation details

### ISSUE THREAD

**Issue by m1kal** [exercism/clojure#430]
There are two problems with this exercise, but I think they can be fixed under a single issue. In my opinion both are related to unnecessary exposure of implementation details.

First, the stub contains `annual-yield`, which is not covered by any test case. Stub should contain only functions that are tested, other (helper) functions are implementation details.

Second, the test:

    (deftest annual-balance-update-large-positive-balance-test
      (is (= 1016.2101016209999M (interest-is-interesting/annual-balance-update 1000.0001M))))

checks if the implementation made a particular numerical error. Both input and output are BigDecimals, so the correct answer could be 1016.210101621M as well. Although it is reasonable to assume most solutions make this mistake, other tests such as

    (deftest annual-balance-update-small-positive-balance-test
      (is (= 0.000001005M (interest-is-interesting/annual-balance-update 0.000001M))))

can fail due to rounding errors.

**Comment by porkostomus** [comment]
Thank you for the feedback! I ported this exercise from [the C# version](https://github.com/exercism/csharp/blob/main/exercises/concept/interest-is-interesting/InterestIsInterestingTests.cs) which does indeed calculate `1016.210101621m`. I was confused why I was getting a different result, and never really got to the bottom of it.

**Comment by m1kal** [comment]
Thanks!
The changes look good.
