### ISSUE TITLE
project.clj appears to be missing in some exercises

### ISSUE THREAD

**Issue by SaschaMann** [exercism/clojure#435]
_These are from the bug report dump on Slack_

---

No project.clj in offline workspaces so lein cannot function.-

---

Tried to submit via editor got 2 tests passed and 0 test failures, but submit button is disabled and tells me to resolve test failures.

Form the cars-assemble project root:
Attempting to test locally using `lein test` fails with Couldn't find project.clj, which is needed for test.

Attempting run `(require 'cars-assemble-test)` fails with 
`Could not locate cars_assemble_test__init.class, cars_assemble_test.clj or cars_assemble_test.cljc on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.`

Tried to submit via CLI  and got 
----- Error --------------------------------------------------------------------
Type:     clojure.lang.ExceptionInfo
Message:  Could not resolve symbol: src/cars_assemble.clj
Location: /mnt/exercism-iteration/src/cars_assemble.clj:21:33
Phase:    analysis

----- Context ------------------------------------------------------------------
17: (defn working-items
18:       "Calculates how many working cars are produced per minute"
19:       [speed]
20:       (-> (production-rate 6)
21:           (/ 60)exercism submit src/cars_assemble.clj
                                    ^--- Could not resolve symbol: src/cars_assemble.clj
22:           int))

---

This project does not include a project.clj and so does not run. Also, I have completed a number of Clojure tasks already, so locking all available tasks and forcing me back to the beginning is a VERY! frustrating experience!!!!

---

when running the tests from the page, they fail with the message " couldn't find project.clj, which is needed for test"

---

Clojure NOOB here, but I think a couple of issues...
1. The local download version does not include a project.clj. This prevents the proper use of leiningen until one is manually added;  i.e, no lein test.
2. The testing rig seems to have an error in the (deftest list-add-test) test. In the test the ->> operator is used but creates an error, while the -> operator runs as I would expect. I believe -> is needed instead of -->.
3. After running the tests via the online editor, the editor shows a red banner with 0 test failures and 4 tests passed. There is no indication that something did not pass or that there was an error, except maybe the red banner thing.

Steps taken...
1. Downloaded the project via the exercism cli
2. Manually added a project.clj
3. Coded the solution, kept getting an error on the aforementioned test due to it wanting to process the string before the list.
4. Changed the --> to -> and reran the tests, which passed.
5. So I think an error in the testing rig vs my code.

**Comment by porkostomus** [comment]
Thanks :) This was fixed by https://github.com/exercism/clojure/pull/414
