### ISSUE TITLE
Cars assemble test failure

### ISSUE THREAD

**Issue by yoleoagain** [exercism/clojure#453]
I have test failure with equal float values.
`Expected (= 1392.3 (cars-assemble/production-rate 7)) but got (not (= 1392.3 1392.3))`

This is my solution:
```clojure
(ns cars-assemble)

(def cars-per-hour 221)

(defn p-in-h-rate [h]
  "Getting percentage rate per hour"
  (cond
    (= h 0) 0
    (<= 1 h 4) 100
    (<= 5 h 8) 90
    (= h 9) 80
    (= h 10) 77
    :else 0))

(defn production-rate
  "Returns the assembly line's production rate per hour,
   taking into account its success rate"
  [speed]
  (float
    (* (/ (* cars-per-hour speed) 100) (p-in-h-rate speed))))

(defn working-items
  "Calculates how many working cars are produced per minute"
  [speed]
  (int (/ (production-rate speed) 60)))
```

Link on task: [https://exercism.org/tracks/clojure/exercises/cars-assemble](url)

**Comment by timothyclin** [comment]
I have a similar problem for test cases 4, 5 and 6 
Test 4 

Code Run

(testing "Production rate for speed 7" (is (= 1392.3 (cars-assemble/production-rate 7))))

Test Failure

Expected (= 1392.3 (cars-assemble/production-rate 7)) but got (not (= 1392.3 1392.3))


Test 5
production-rate-speed-9-test
Code Run

(testing "Production rate for speed 9" (is (= 1591.2 (cars-assemble/production-rate 9))))

Test Failure

Expected (= 1591.2 (cars-assemble/production-rate 9)) but got (not (= 1591.2 1591.2))

Test 6
production-rate-speed-10-test
Code Run

(testing "Production rate for speed 10" (is (= 1701.7 (cars-assemble/production-rate 10))))

Test Failure

Expected (= 1701.7 (cars-assemble/production-rate 10)) but got (not (= 1701.7 1701.7))

**Comment by p0w1nd** [comment]
I also encounter this test failure. The output is:

lein test cars-assemble-test

lein test :only cars-assemble-test/production-rate-speed-9-test

FAIL in (production-rate-speed-9-test) (cars_assemble_test.clj:23)
Production rate for speed 9
expected: (= 1591.2 (cars-assemble/production-rate 9))
  actual: (not (= 1591.2 1591.2))

lein test :only cars-assemble-test/production-rate-speed-10-test

FAIL in (production-rate-speed-10-test) (cars_assemble_test.clj:27)
Production rate for speed 10
expected: (= 1701.7 (cars-assemble/production-rate 10))
  actual: (not (= 1701.7 1701.7))

lein test :only cars-assemble-test/production-rate-speeed-7-test

FAIL in (production-rate-speeed-7-test) (cars_assemble_test.clj:19)
Production rate for speed 7
expected: (= 1392.3 (cars-assemble/production-rate 7))
  actual: (not (= 1392.3 1392.3))

Ran 12 tests containing 12 assertions.
3 failures, 0 errors.
Tests failed.

**Comment by p0w1nd** [comment]
Looking at the `cars_assemble_test.clj` file:

```
(ns cars-assemble-test
  (:require [clojure.test :refer [deftest testing is]]
            cars-assemble))

(deftest production-rate-speed-0-test
    (testing "Production rate for speed 0"
      (is (= 0.0 (cars-assemble/production-rate 0)))))

(deftest production-rate-speed-1-test
    (testing "Production rate for speed 1"
      (is (= 221.0 (cars-assemble/production-rate 1)))))

(deftest production-rate-speed-4-test
    (testing "Production rate for speed 4"
      (is (= 884.0 (cars-assemble/production-rate 4)))))

(deftest production-rate-speeed-7-test
    (testing "Production rate for speed 7"
      (is (= 1392.3 (cars-assemble/production-rate 7)))))

(deftest production-rate-speed-9-test
  (testing "Production rate for speed 9"
    (is (= 1591.2 (cars-assemble/production-rate 9)))))

(deftest production-rate-speed-10-test
    (testing "Production rate for speed 10"
      (is (= 1701.7 (cars-assemble/production-rate 10)))))

(deftest working-items-speed-0-test
    (testing "Working items for speed 0"
      (is (= 0 (cars-assemble/working-items 0)))))

(deftest working-items-speed-1-test
    (testing "Working items for speed 1"
      (is (= 3 (cars-assemble/working-items 1)))))

(deftest working-items-speed-5-test
    (testing "Working items for speed 5"
      (is (= 16 (cars-assemble/working-items 5)))))

(deftest working-items-speed-8-test
    (testing "Working items for speed 8"
      (is (= 26 (cars-assemble/working-items 8)))))

(deftest working-items-speed-9-test
    (testing "Working items for speed 9"
      (is (= 26 (cars-assemble/working-items 9)))))

(deftest working-items-speed-10-test
    (testing "Working items for speed 10"
      (is (= 28 (cars-assemble/working-items 10)))))

```

I conclude that using `=` to compare floating-point numbers have 2 results:
- If both numbers are `x.0` and `x.0` => `=` returns true
- If both numbers are `x.k` and `x.k` but k is not 0 => `=` returns false which is not expected (on the other hand, as far as I know it's not a good practice to compare floating-point numbers with `=` because internally they're not accurate like that)

**Comment by porkostomus** [comment]
@yoleoagain your solution fails because you're comparing doubles and floats. It works if you change it to this:

```clojure
(defn production-rate [speed]
  (double
    (* (/ (* 221 speed) 100) (p-in-h-rate speed))))
```

**Comment by p0w1nd** [comment]
@porkostomus Oh, it works great with `double`. And it's good to know that we can cross-check the type of the numbers using `type`. Thanks!

Anyway, in the Instructions section of this exercise it states that `Note that the value returned is a float.` This may make the reader confused. Should it be changed to `double`, or is it intentionally for the reader to find out about `float` vs. `double` as you've just explained above?

**Comment by porkostomus** [comment]
Yeah you're right that part does seem like it could be misleading. Maybe it should explicitly say it's a `java.lang.Double`.

**Comment by tosh** [comment]
I ran into the same issue just now, might make sense to change the wording in the instructions from "float" to "double" or to make the test cases more lenient

**Comment by BTowersCoding** [comment]
Thanks for the bump, I just made a PR with the change

**Comment by yoleoagain** [comment]
> @yoleoagain your solution fails because you're comparing doubles and floats:
> 
> ```clojure
> user=> (type 1392.3)
> java.lang.Double
> 
> user=> (type (production-rate 7))
> java.lang.Float
> ```
> 
> It works if you change it to this:
> 
> ```clojure
> (defn production-rate [speed]
>   (double
>     (* (/ (* 221 speed) 100) (p-in-h-rate speed))))
> ```

Thanks a lot!!!!
