### ISSUE TITLE
Typo: "abouts"

### ISSUE THREAD

**Issue by joachimnielandt** [exercism/clojure#459]
https://github.com/exercism/clojure/blob/f10180101a8182fd5ceb862d2bdf0fd5a67920d9/exercises/concept/tracks-on-tracks-on-tracks/.meta/config.json#L2

`abouts` should be `about`, I'm assuming. Not sure I should make a pull request for this, or an issue. Perhaps I'll learn by doing :).

**Comment by porkostomus** [comment]
Good catch. A PR would be welcome, thanks :)
