### ISSUE TITLE
Rotational Cipher Tests differ from description

### ISSUE THREAD

**Issue by BlueBrightStar** [exercism/clojure#506]
in https://exercism.org/tracks/clojure/exercises/rotational-cipher, the problem description in the Instructions clearly states that valid cipher values are between 0 and 26, but the test suite includes negative numbers being treated as valid inputs - such as one testing that it returns the 'correct' value for a key of -2. 
Please change the description of the problem or remove the tests to make it clearer.

**Comment by tasxatzial** [comment]
The current specs don't include checks for negative shifts. @bobbicodes May i sync/update the tests and remove those?

**Comment by bobbicodes** [comment]
Sure :)
