### ISSUE TITLE
Complex Numbers: Tests mix up Expected and Actual results, and unclear about requiring floats rather than rationals

### ISSUE THREAD

**Issue by SebAlbert** [exercism/clojure#520]
The tests for the Complex Numbers exercise have the Expected and Actual results in the wrong order in their `(is)` forms.
Moreover, it could be made more explicit that floats are expected when doing division rather than rational numbers (especially if the test suite output suggests that it would be the other way around).

**Comment by BTowersCoding** [comment]
Thanks again, I can't take the blame for this one because I didn't write it :)

This makes me wonder how many other test suites have the expected/actual args reversed. This must be a pretty common mistake.
