### ISSUE TITLE
Bank Account problem under wrong concept?

### ISSUE THREAD

**Issue by asifm** [exercism/clojure#550]
In the [concepts](https://exercism.org/tracks/clojure/concepts) section, the [_Bank Account_](https://exercism.org/tracks/clojure/exercises/bank-account) problem is under _Floating-Point Numbers_ concpet. The problem doesn't seem to have anything to do with floating points. Perhaps we can create a new concept cateogry for such problems: _Concurrency_ or _Advanced_ or something like that?

**Comment by bobbicodes** [comment]
Created #551 , but I think we can create the concurrency concept.

The way I see it, the exercise is essentially about atoms, though I've seen some folks use agents, since they seem to fit the description better.
