### ISSUE TITLE
New concept: deriving new functions from existing functions (partial, comp, memoize)

### ISSUE THREAD

**Issue by JaumeAmoresDS** [exercism/clojure#588]
Would there be interest in creating a concept dedicated to function tools such as comp, partial, memoize, that facilitate deriving new functions from existing ones?

**Comment by JaumeAmoresDS** [comment]
@bobbicodes, I just created a PR from my fork, but I don't see it in the list of PRs in the main branch. This is the first time I do a PR from a fork and I'm not sure if I did it correctly? I also tried to select the reviewer but couldn't unfortunately...

The PR includes only the new concept, not the exercises, at this point in time... should I wait until I include exercises and create a new PR?

**Comment by bobbicodes** [comment]
We could merge the concept now to get that out of the way... I reopened the PR so I'll comment over there.

**Comment by JaumeAmoresDS** [comment]
Hi @bobbicodes, I was just thinking about possible exercises, and I have some that might be appropriate. However, I realize that basically anything that one can do with `partial`, can be done with an anonymous function, at least for solving those exercises. A similar thing happens with `comp`, where one can use a direct composition of functions rather than using this construct, and also with `juxtp`. They all seem to add syntactic sugar and be a convenience that one can opt to not use (there might be situations where they are strictly required but I can't think of them). 

My question is: to what extent is this important? Is there a way to enforce the use of those specific functions when testing an exercise, e.g, through the analyzers / representers that are discussed by the Exercism team?

**Comment by JaumeAmoresDS** [comment]
In order to be specific, I include here a very rough description of the exercises.

We have Mary and John, who do frequent trips by bike: 

- They want to calculate their average speed based on their recent trips, where the input is the distance from one destination to the next and how long it took to reach that destination. 
- Based on their average speed, they want to estimate how long it will take to perform their next planned trips. The input for each trip is a list of distances between destinations. For example, one of the next planned trips is from Paris to Lyon, then from Lyon to Milan, then from Milan to Rome: they have the distances between each pair of cities, and they can build a list of distances based on that, something like

```clojure 
'(800, 500, 300)
```
1. Use `partial` to make this calculation any time they want to plan a new trip.
2. Use `comp` to update their average speed and then apply the updated speed to estimate the total time it will take to do a new trip they have in mind.
3. Use `juxtp` to evaluate different trips that they are considering, in terms of how long it would take each of one. The input would be a list of distances for each trip, and the output the total time required.

The idea is that `comp` is typically used (AFAIK) with a single input from the second function onwards, so that we need to use `partial` (or an anonymous function) as part of `comp`. I think a similar thing happens with `juxtp`, but I'm not sure about that.

While estimating the total times for each potential trip, they may want to play a bit with the trips, and add, modify, or remove destinations several times. Sometimes they might end up with the original trip, and they don't want to have to annotate the previously computed distances. Let's imagine that calculating the time it takes to go from one destination to another one is computationally expensive. We can use memoize to compute those times, so we save computational cost when requiring those results again. Then we can have a function that, given a potentially long list of cities, calculates the total estimated time for that trip. They would be evaluating many potential lists (one for each trip, where they have many possible trips in mind, and for each trip they would be playing with many possibilities, i.e., changing the list of cities many times and calculating their total time). We can also use memoize, not only for the pairwise times, but for the total time, in case the list is repeated while exploring the possibilities.

A final task might be a group of people that bet on which couple will be making the same trip faster, based on the average speed of each couple. Here we could use `map` and `partial`, where `map` takes a list of partial functions, one for each couple, and the total distance of the trip. Again, anonymous functions could be used here instead of partial ones...

Please let me know your thoughts! Thank you very much for your help.

**Comment by bobbicodes** [comment]
> ...I realize that basically anything that one can do with partial, can be done with an anonymous function, at least for solving those exercises. A similar thing happens with `comp`...

It's funny that you say this because I actually never use `comp` or `partial` in my own code, and whenever I see them I compulsively have to change them to anonymous functions because they make so much more sense to me! I've heard others say similarly, so I've never been motivated to use them. The one exception I've seen is when using `comp` with transducers, but that's obviously out of scope for this exercise.

`juxt` is different, though, there are some very useful patterns with it... years ago I even did a recurring blog series called [just-juxt](https://porkostomus.gitlab.io/tags-output/juxt/) where every day I posted a new solution using `juxt`, but theh Tl;DR is it comes in handy any time you want to generate a sequence of pairs.

So far we haven't enforced the usage of the concepts so it's been on the student to get the intended lesson out of the exercise. For example, in the exercise teaching the Java `Character` class, I've seen students solve it using regex. This could be addressed with an exercise-specific analyzer, but for now I wouldn't worry about it.

**Comment by tasxatzial** [comment]
Resolved in https://github.com/exercism/clojure/pull/589
