### ISSUE TITLE
Exercises to port

### ISSUE THREAD

**Issue by BNAndras** [exercism/clojure#606]
I'd like to port the following exercises as a starting place.

- [ ] affine-cipher
- [ ] custom-set
- [ ] darts
- [ ] dnd-character
- [ ] high-scores
- [x] list-ops
- [ ] pop-count
- [ ] resistor-color
- [ ] resistor-color-duo
- [ ] square-root

**Comment by kahgoh** [comment]
Hey @BNAndras, I'd like to see if I can port list-ops for the Clojure track

**Comment by kahgoh** [comment]
Actually, nevermind, I just realized there is an existing PR for it (#552)

**Comment by BNAndras** [comment]
That PR seems a bit stale. Perhaps check with Bobbi if they'd be interested in having you continue working on it.

**Comment by BNAndras** [comment]
I mean the exercise-specific portion of the PR. I wouldn't know about the test generator portion.
