### ISSUE TITLE
Documentation: Editors

### ISSUE THREAD

**Issue by canweriotnow** [exercism/clojure#62]
So, I happened to announce the elisp track on the #editors channel on the Clojurians Slack... someone mentioned how neat it would be to manage exercises from within an IDE (he's using Cursive w/ IntelliJ) and I mentioned the exercism.el package I started and stalled on...

Anyhow, it got me thinking it might be extremely helpful to have a help page on editors & configuration, not sure if this should go in the getting-started-with-clojure help section or somewhere else... should we have this? Thoughts?

**Comment by kytrinyx** [comment]
Oh, my. Yes, this would be very, very good. Probably in https://github.com/exercism/docs/tree/master/app/pages/topics

**Comment by nellshamrell** [comment]
Hi @kytrinyx!  I noticed that link is no longer working, is there any updated place that would be good for this documentation?  Would love to take a crack at this :)

**Comment by kytrinyx** [comment]
I think we should probably have a whole new topic for this. We currently have a "/help" page (http://exercism.io/help), but that's specifically about troubleshooting.

What do you think of renaming "/help" to "/help/troubleshooting" and then adding "/help/editors" as a separate page? Take a look at https://github.com/exercism/exercism.io/blob/master/app/routes/static.rb#L16 and go from there to see how we've put together the view (there's some markdown in `x/docs/md/...` that we pull in. It's not awesome, but once you find your way around it, it's also not awful.
