### ISSUE TITLE
New maintainers.

### ISSUE THREAD

**Issue by iHiD** [exercism/clojure#660]
@michalporeba and @tasxatzial: You both qualify to be maintainers of Clojure! Thanks for your hard work. Would you be happy to be appointed? :)

**Comment by michalporeba** [comment]
Hi @iHiD, I'd be happy to help. 
Is there a set list of responsibilities other than generally maintaining the clojure repo and the language track?

**Comment by iHiD** [comment]
Awesome. Thanks! No, no extra responsibilities really. You get access to a Discord channel and extra GH permissions, but other than that, keep doing the same good stuff :)

**Comment by ErikSchierboom** [comment]
Awesome. Thank you both!

You should receive an invite to join the org and the team now. You'll also get access to the #maintainers channel on Discord if your Exercism and Discord accounts [are linked](https://exercism.org/settings/integrations).

You can learn more about being a maintainer [here](https://exercism.org/docs/community/maintainers)

Thanks so much for your work, and welcome to the team :)
